version: "3.9"

services:
  server:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - data:/var/lib/postgresql/data

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contact_db
    ports:
      - 6001:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
