version: "3.9"

services:
  server:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data
    command: bash -c "npm run migrate && npm run start"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contact_db
    ports:
      - 6001:5432
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

networks:
  default: {}
